version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r hello_world.zip lambda_function.py
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name hello_world --zip-file fileb://hello_world.zip
    

artifacts:
  type: zip
  paths:
    - '*'
